# Generated by Django 2.0.4 on 2018-06-17 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='', max_length=280)),
                ('dia', models.DateField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('edad', models.IntegerField(default=18)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('vicitas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Appointment')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo en tienda'), ('Transferencia', 'Transferenci bancaria'), ('Paypal', 'Paypal')], default='Efectivo', max_length=13)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Client'),
        ),
    ]
