# Generated by Django 2.0.4 on 2018-06-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180617_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.TimeField(),
        ),
    ]
